# frozen_string_literal: true

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/damoncoo/XYSepc.git'

use_frameworks!

platform :ios, '10.0'

target 'YiCore_Example' do
  pod 'YiCore', path: '../'

  target 'YiCore_Tests' do
    inherit! :search_paths
#
#    pod 'Quick', '~> 2.2.0'
#    pod 'Nimble', '~> 8.0.7'
#    pod 'FBSnapshotTestCase', '~> 2.1.4'
#    pod 'Nimble-Snapshots', '~> 8.0.0'
  end
end
